DROP DATABASE IF EXISTS employee_db;

CREATE DATABASE employee_db;

USE employee_db;

CREATE TABLE department(
dept_id INTEGER AUTO_INCREMENT,
name VARCHAR (30) NOT NULL,
PRIMARY KEY (dept_id)
);

CREATE TABLE role(
role_id INTEGER AUTO_INCREMENT PRIMARY KEY,
title VARCHAR (30) NOT NULL,
salary DECIMAL NOT NULL,
dept_id INTEGER,
FOREIGN KEY(dept_id) REFERENCES department(id)
);

CREATE TABLE employee(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR (30) NOT NULL,
last_name VARCHAR (30) NOT NULL,
role_id INTEGER,
FOREIGN KEY(role_id) REFERENCES role(id),
manager_id INTEGER
);


